{% set version = "2019.1.0" %}

package:
  name: fenics-ffc
  version: {{ version }}

source:
  url: https://bitbucket.org/fenics-project/ffc/downloads/ffc-{{ version }}.tar.gz
  sha256: 4ff821a234869d8b9aaf8c5d7f617d42f9c134a2529e76c9519b681dff35affd
  patches:
    - ufc-include-path.patch
    - numpy-prod.patch

build:
  number: 40
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
    - mkdir -p $PREFIX/include
    - cp ffc/backends/ufc/*.h $PREFIX/include/

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - fenics-dijitso =={{ version }}
    - fenics-fiat =={{ version }}
    - fenics-ufl =={{ version }}
test:
  imports:
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
  commands:
    - ffc --help
    - test -f $PREFIX/include/ufc.h
    - test -f $PREFIX/include/ufc_geometry.h


about:
  home: https://www.fenicsproject.org
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: 'The FEniCS Form Compiler'

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (https://fenicsproject.org). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: https://fenics.readthedocs.io
  dev_url: https://bitbucket.org/fenics-project/

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
    - jan-janssen
